### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by lfolco** [WURFL/magento-imageengine-extension#16]
Any plans to support PHP 8.2?

**Comment by jonarnes** [comment]
Thank you for your request. 
Yes! we do have plans. Stay tuned.

**Comment by lfolco** [comment]
Great! Do you have a rough timeline for when it will be ready?

**Comment by jonarnes** [comment]
Expect it to be available in a couple of weeks.

**Comment by mihaimatei** [comment]
Resolved by PR #17 , available in latest release [v1.0.24](https://github.com/WURFL/magento-imageengine-extension/releases/tag/v1.0.24)
