### ISSUE TITLE
Instructions have typo for installing module

### ISSUE THREAD

**Issue by maderlock** [WURFL/magento-imageengine-extension#21]
The composer instruction is correct, but the Magento name of the module is not the same. This is the line that is failing for me:

    magento module:enable scientiamobile/module-magento2-image-cdn-imageengine

That gives the error `Unknown module(s): 'scientiamobile/module-magento2-image-cdn-imageengine'`

It looks like the composer packagist string got used instead of the module vendor/name. Looking in registration.php, I can see that the Magento module name is `ScientiaMobile_IO`. Also, as the previous command was designed to be run from the top-level, it's common to run magento from there too, making the correct line:

    ./bin/magento module:enable ScientiaMobile_IO

Though this line is commonly skipped as just running `./bin/magento setup:upgrade` will enable the module and also install it. Without any data or schema instructions, this is not required, but in case you later have this it's good to include in the instructions.

**Comment by jonarnes** [comment]
Thank you very much for your feedback!
We'll look into this ASAP and release a fix

**Comment by jonarnes** [comment]
@maderlock, a fix is now released https://packagist.org/packages/scientiamobile/module-magento2-image-cdn-imageengine
