### ISSUE TITLE
PHP 8.3 version bump

### ISSUE THREAD

**Issue by jonarnes** [WURFL/magento-imageengine-extension#23]
SUMMARY:
As a customer I am updating my Magento sites to 2.4.7 and PHP 8.3, but ImageEngine extension for Magento 2 does not support PHP 8.3.

The latest release of ImageEngine extension for Magento 2, version 1.0.26, does not list PHP 8.3 as supported:
[scientiamobile/module-magento2-image-cdn-imageengine - Packagist](https://packagist.org/packages/scientiamobile/module-magento2-image-cdn-imageengine#1.0.26) 

Magento added PHP 8.3 support starting with release 2.4.7: 
[System requirements | Adobe Commerce](https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements)
[Magento Open Source 2.4.7 release notes | Adobe Commerce](https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/magento-open-source/2-4-7)

Verify that the module works on newer PHP versions.

**Comment by mihaimatei** [comment]
Resolved by #24 , tested with PHP 8.3 and Magento 2.4.7. Released as https://github.com/WURFL/magento-imageengine-extension/releases/tag/v1.0.27.
